tasks:
  - init: composer global require laravel/installer 
          && composer create-project --prefer-dist etec 
          && cd etec 
          && composer create-project phpmyadmin/phpmyadmin 
          ;
    command: cd phpmyadmin && php -S localhost:8080
image:
  file: .gitpod.Dockerfile
