tasks:
  - init: composer global require laravel/installer 
          && composer create-project --prefer-dist laravel/laravel
          && composer create-project phpmyadmin/phpmyadmin
          && mysqladmin -u root password 'gitpod'
command: cd laravel && php artisan serve
image:
  file: .gitpod.Dockerfile
