tasks:
  - init: composer global require laravel/installer 
          && composer create-project --prefer-dist laravel/laravel etec 
          && cd etec 
          && composer create-project phpmyadmin/phpmyadmin
          && cd .. && mysqladmin -u root password 'gitpod'
          ;
    command: cd etec/phpmyadmin && php -S localhost:8080
image:
  file: .gitpod.Dockerfile
